# Generated by Django 5.0.6 on 2024-06-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='nombre',
        ),
    ]
