# Generated by Django 5.0.6 on 2024-06-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_rename_marca_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreMarca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.marca', verbose_name='Marca'),
        ),
    ]
